import { open, readJson } from './harness.mjs';
import fs from 'fs';
const log = (...a) => console.log(...a);
const old = readJson('old_state.json');
// ---- A: desktop, look-back from Google Sheet and from the page store; PDF / Excel of an old revision; bring back to edit ----
let t = await open({ docs: old.db, gsFiles: old.files }), page = t.page;
await page.click('#btn-hist'); await page.waitForTimeout(900);
log('A sources:', (await page.locator('#h-src option').allInnerTexts()).join(' || '));
log('A months:', (await page.locator('#h-month option').allInnerTexts()).join(','), '| rows:', await page.locator('#h-list .hrow').count());
await page.locator('#h-list .hrow').nth(1).click(); await page.waitForTimeout(900);
log('A view:', await t.txt('#h-title'), '|', await t.txt('#h-sub'));
await page.click('#panel-hist [data-act=hpdf]'); await page.waitForTimeout(2500);
await page.click('#panel-hist [data-act=hxlsx]'); await page.waitForTimeout(800);
log('A files:', (await page.evaluate(() => window.__saved.map((f) => f.filename + ' ' + Math.round(f.b64.length * 0.75 / 1024) + 'KB'))).join(' | '), '| info:', await t.txt('#h-vinfo'));
await page.screenshot({ path: t.out('v6-hist.png'), fullPage: true });
await page.selectOption('#h-src', 'page'); await page.waitForTimeout(700);
log('A page-store rows:', await page.locator('#h-list .hrow').count(), '| info:', await t.txt('#h-info'));
await page.selectOption('#h-month', '2026-09'); await page.waitForTimeout(200);
log('A month filter 2026-09:', await page.locator('#h-list .hrow').count());
await page.evaluate(() => { window.__saved.length = 0; });
await page.click('#panel-hist [data-act=sdb]'); await page.waitForTimeout(1200);
log('A db export:', (await page.evaluate(() => window.__saved.map((f) => f.filename))).join(','), '| info:', await t.txt('#h-info'));
await page.locator('#h-list .hrow').first().click(); await page.waitForTimeout(700);
await page.click('#panel-hist [data-act=hedit]'); await page.waitForTimeout(300); log('A edit dialog:', (await t.dlgText()).slice(0, 160)); await t.ok(); await page.waitForTimeout(300);
log('A edit page date:', await page.inputValue('#f-dateFrom'), '| status:', await t.txt('#save-status'));
await page.click('#btn-save'); await page.waitForTimeout(900);
log('A save unchanged old report →', (await t.dlgText()).slice(0, 120)); await t.ok();
log('errors A:', JSON.stringify(t.errors));
await t.browser.close();
// ---- B: no connector in this view ----
t = await open({ docs: old.db, gsFiles: old.files, nomcp: true }); page = t.page;
await t.type('#f-dateFrom', '2026-10-06');
await page.click('#btn-save'); await page.waitForTimeout(1500);
log('B gs-line:', (await t.txt('#gs-line')).replace(/\n/g, ' ~ '), '| chip:', await page.locator('#gs-chip').innerText());
log('errors B:', JSON.stringify(t.errors));
await t.browser.close();
// ---- C: phone, dark; new fiscal year banner ----
t = await open({ docs: old.db, gsFiles: old.files, mobile: true, dark: true, now: '2027-10-01T03:00:00Z', keep: true }); page = t.page;
await page.screenshot({ path: t.out('v6-m-remind.png') });
await t.cancel(); await page.waitForTimeout(200);
await page.screenshot({ path: t.out('v6-m-top.png') });
const ov = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
log('C horizontal overflow px:', ov);
await page.click('#btn-hist'); await page.waitForTimeout(900);
await page.locator('#h-list .hrow').first().click(); await page.waitForTimeout(900);
await page.evaluate(() => window.scrollTo(0, 0)); await page.waitForTimeout(100);
await page.screenshot({ path: t.out('v6-m-hist.png') });
log('C overflow in hist:', await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth));
log('errors C:', JSON.stringify(t.errors));
await t.browser.close();
