import { open, readJson, PW } from './harness.mjs';
import fs from 'fs';
const log = (...a) => console.log(...a);
const live = readJson('live_state.json');
// the live state plus BACKUP files for 69 and 70 already set, opened on the first day of FY 71
const t0 = await open({ docs: live.db, gsFiles: live.files }); let page = t0.page;
const setBk = async (tt, fy, id) => { await tt.page.click('#gs-chip'); await tt.page.waitForTimeout(250); await tt.page.fill('#dlg input[name=fy]', fy); await tt.page.fill('#dlg input[name=blink]', id); await tt.pass(PW.sheet); await tt.page.waitForTimeout(6000); };
await setBk(t0, '70', t0.BK_B); await setBk(t0, '69', t0.BK_A);
const st = await page.evaluate(() => ({ files: window.__gs.files, db: window.__db }));
await t0.browser.close();
const t = await open({ docs: st.db, gsFiles: st.files, now: '2027-10-01T03:00:00Z', keep: true }); page = t.page;
const n = async (file) => { const o = []; for (const k of ['ARCHIVE', 'DATA', 'SUMMARY']) { const x = await t.tab(k, file); o.push(x ? x.rows.length : '-'); } return o.join('/'); };
const db = (k) => page.evaluate((k) => window.__db[k], k);
log('A reminder:', (await t.dlgText()).slice(0, 330));
await t.cancel(); await page.waitForTimeout(150);
log('A banner:', (await t.txt('#fy-note')).replace(/\n/g, ' ~ '), '| chip:', await t.txt('#gs-chip'));
await t.type('#f-dateFrom', '2027-10-01');
await t.type('#f-a319-af', String(+(await page.inputValue('#f-a319-af') || await page.getAttribute('#f-a319-af', 'placeholder')) + 2));
await page.click('#btn-save'); await page.waitForTimeout(2200);
log('B gs-line:', (await t.txt('#gs-line')).replace(/\n/g, ' ~ '));
log('B rows B', await n(t.FILE_B), 'BK_B', await n(t.BK_B), '| parked', JSON.stringify((await db('app/sheets')).parked), '| bpending', JSON.stringify((await db('app/sheets')).bpending));
await page.click('#panel-saved [data-act=back]'); await page.waitForTimeout(150);
await page.click('#fy-note [data-act=gs]'); await page.waitForTimeout(250);
log('C fy default:', await page.inputValue('#dlg input[name=fy]'));
await page.fill('#dlg input[name=link]', t.FILE_C); await page.fill('#dlg input[name=blink]', t.BK_C); await t.pass(PW.sheet); await page.waitForTimeout(8000);
log('C toast:', await t.txt('#toast'));
log('C rows B', await n(t.FILE_B), 'BK_B', await n(t.BK_B), '| C', await n(t.FILE_C), 'BK_C', await n(t.BK_C), '| parked', JSON.stringify((await db('app/sheets')).parked), '| bpending', JSON.stringify((await db('app/sheets')).bpending));
log('C ids C:', (await t.tab('ARCHIVE', t.FILE_C)).rows.map((r) => r[0]).join(','), '| BK_C:', (await t.tab('ARCHIVE', t.BK_C)).rows.map((r) => r[0]).join(','), '| BK_B has FY71 row:', (await t.tab('ARCHIVE', t.BK_B)).rows.some((r) => String(r[0]).startsWith('r2027')));
log('C banner hidden:', await page.locator('#fy-note').isHidden(), '| chip:', await t.txt('#gs-chip'), '| doc keys:', JSON.stringify([Object.keys((await db('app/sheets')).files), Object.keys((await db('app/sheets')).backups)]));
log('errors:', JSON.stringify(t.errors));
await t.browser.close();
