import { open, readJson } from './harness.mjs';
import fs from 'fs';
const log = (...a) => console.log(...a);
const old = readJson('old_state.json');
const t = await open({ docs: old.db, gsFiles: old.files }), page = t.page;
const st = async (id) => { const el = page.locator('#' + id); return ((await el.getAttribute('class')) || '').includes('over') ? 'OVER' : 'ok'; };
const pop = (id) => page.evaluate((id) => { const w = document.getElementById(id).parentNode, ps = w.matches('.cb') ? '::before' : '::after', c = getComputedStyle(w, ps); return w.className + ' ' + ps + ' ' + c.content + ' display=' + c.display; }, id);
log('start (saved data): sched', await page.inputValue('#f-a320_05-sched'), await st('f-a320_05-sched'), '| SCHEDULE', await st('f-a320_03-sched'), '| check A/C PRESERVATION', await st('f-ssj_06-check'), '| HANGAR QUEEN', await st('f-ssj_08-check'));
const set = async (id, v) => { await page.fill('#' + id, v); await page.locator('#' + id).blur(); await page.waitForTimeout(120); };
await set('f-a319-sched', 'WAITING'); log('sched WAITING:', await st('f-a319-sched'));
await set('f-a319-sched', 'WAITING PARTS'); log('sched WAITING PARTS:', await st('f-a319-sched'));
await set('f-a319-sched', 'UNSCHEDULE'); log('sched UNSCHEDULE typed:', await st('f-a319-sched'));
await set('f-a319-sched', 'WAITING PARTS');
await set('f-a319-check', 'SPECIAL INSPECTION'); log('check SPECIAL INSPECTION:', await st('f-a319-check'));
await set('f-a319-check', 'SPECIAL INSPECTION AFTER BIRD STRIKE'); log('check long:', await st('f-a319-check'));
await set('f-ac-a319-notes-0', 'รอ TG ยืนยัน'); log('note short:', await st('f-ac-a319-notes-0'));
await set('f-ac-a319-notes-0', 'หมายเหตุยาวปานกลาง รอ TG ยืนยันวันเข้า'); log('note long:', await st('f-ac-a319-notes-0'));
await page.hover('#f-a319-sched'); await page.waitForTimeout(150); log('hover sched popup:', await pop('f-a319-sched'));
await page.hover('#f-a319-check'); await page.waitForTimeout(150); log('hover check popup:', await pop('f-a319-check'));
await page.hover('#f-ac-a319-notes-0'); await page.waitForTimeout(150); log('hover note popup:', await pop('f-ac-a319-notes-0'));
await page.hover('#f-a320_05-sched'); await page.waitForTimeout(150); log('hover UNSCHEDULE popup:', await pop('f-a320_05-sched'));
await page.hover('#f-a319-check'); await page.waitForTimeout(150);
const box = await page.locator('[data-ac="a319"]').boundingBox();
await page.screenshot({ path: t.out('v9-flags.png'), clip: { x: box.x, y: box.y, width: box.width, height: Math.min(box.height + 10, 330) } });
await set('f-a319-check', '6M-CHECK'); log('back to 6M-CHECK:', await st('f-a319-check'), await pop('f-a319-check'));
log('errors:', JSON.stringify(t.errors));
await t.browser.close();
